name: Deploy on Fly

on:
  workflow_run:
    workflows: ["Laravel"]
    types:
      - completed

jobs:
  deploy_on_fly:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Fly.io
      run: |
        curl -L https://fly.io/install.sh | sh
        export PATH="/home/runner/.fly/bin:$PATH"
    - name: Execute deploy
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      run: |
        flyctl auth token $FLY_API_TOKEN
        flyctl deploy
